version: "3"
services:
  db:
    image: mysql
    container_name: 'mysql_db'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init_data:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=world
      - MYSQL_USER=zose
      - MYSQL_PASSWORD=zose